[package]
name = "waveutil"
version = "0.1.0"
authors = ["Taylor Hornby <taylor@defuse.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
